src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  root "home#index"
  get "latest" => "home#latest"
  get "about" => "home#about"
  get "contact" => "home#contact"
  get "markdown_example" => "home#markdown_example"
  resources :items do
    get "search", on: :collection
    patch "like", "unlike", on: :member
  end
  resources :users, only: [:show, :voted] do
    get "voted", on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
  <div class="errors alert alert-danger" role="alert">
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

src/app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <hr>
    <ul class="footer__list">
      <li class="footer__list_item">
        <%= link_to "Seikatsuとは", about_path %>
      </li>
      <li class="footer__list_item">
        <%= link_to "Markdownの書き方", markdown_example_path %>
      </li>
      <li class="footer__list_item">
        <%= link_to "お問い合わせ", contact_path %>
      </li>
      <li class="footer__list_item">
        <a href="https://github.com/TakuyaHanada/Seikatsu">GitHub</a>
      </li>
    </ul>
    <p class="footer__copyright">© 2019 TakuyaHanada</p>
  </div>
</footer>

src/app/views/shared/_header.erb
<header class="header">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand" href="#">Seikatsu</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">ホーム</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">投稿する</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">下書き一覧</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">マイページ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">設定</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

src/app/views/shared/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <%= link_to "Seikatsu", :root, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "ホーム", :root, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "投稿する", [:new, :item], class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", current_user, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "設定", edit_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        <%= form_tag :search_items, method: :get, class: "header__search form-inline my-2 my-lg-0" do %>
          <%= text_field_tag "query", params[:query], class: "header__search_input form-control mr-sm-2", placeholder: "キーワードを入力" %>
          <%= submit_tag "検索", class: "header__search_submit btn btn-primary my-2 my-sm-0" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

src/app/views/shared/_item.html.erb
<div class="item">
  <div class="item_user">
    <%= link_to item.user do %>
      <% if item.user.profile_image.attached? %>
        <%= image_tag item.user.profile_image.variant(resize: "100x100"), class: "item_user-img" %>
      <% else %>
        <%= image_tag "user.png", class: "item_user-img" %>
      <% end %>
      <span class="item_user-name"><%= item.user.name %></span>
    <% end %>
  </div>
  <div>
    <%= link_to item.title, item, class: "item_title" %>
  </div>
  <div>
    <span class="item_released-at">公開日 <%= item.created_at.strftime("%Y年%m月%d日") %></span>
    <span class="item_votes">いいね <%= item.votes.length %></span>
  </div>
</div>

src/app/views/shared/_item_form.html.erb
<section class="item-form tile">
  <%= form_for item do |form| %>
    <%= form.text_field :title, class: "item-form__title form-control", placeholder: "タイトル（30文字以内）" %>
    <div class="item-form__about-markdown">
      <%= link_to "Markdownの書き方", markdown_example_path, target: :_blank%>
    </div>
    <%= form.text_area :body, class: "item-form__body form-control", placeholder: "Markdown記法で記事を書く" %>
    <div class="item-form__submit">
      <%= form.submit btn, class: "btn btn-success item-form__submit_btn" %>
    </div>
  <% end %>
</section>

src/app/views/shared/_user.html.erb
<div class="user-main__about">
  <% if user.profile_image.attached? %>
    <%= image_tag user.profile_image.variant(resize: "100x100"), class: "about_img" %>
  <% else %>
    <%= image_tag "user.png", class: "about_img" %>
  <% end %>
  <div>
    <h1 class="about_name"><%= user.name %></h1>
    <p class="about_desc"><%= user.description %></p>
  </div>
</div>